#!/bin/bash

# Download free stock images for Thida Thai Massage services
# This script downloads high-quality images from Pexels

echo "🖼️  Downloading service images from Pexels..."
echo "================================================"

cd "$(dirname "$0")/public/images" || exit

# Pexels API free images (these are example URLs - you'll need to get actual URLs from Pexels)
# Visit https://www.pexels.com and search for these terms, then copy the download URL

echo "⚠️  MANUAL DOWNLOAD REQUIRED"
echo "Please visit Pexels.com and download the following images:"
echo ""
echo "1. Traditional Thai Massage"
echo "   Search: 'thai massage'"
echo "   Save as: thai-massage-traditional.jpg"
echo "   URL: https://www.pexels.com/search/thai%20massage/"
echo ""
echo "2. Aromatherapy/Oil Massage"
echo "   Search: 'aromatherapy massage oil'"
echo "   Save as: aromatherapy-oil-massage.jpg"
echo "   URL: https://www.pexels.com/search/aromatherapy%20massage/"
echo ""
echo "3. Hot Stone Massage"
echo "   Search: 'hot stone massage'"
echo "   Save as: hot-stone-therapy.jpg"
echo "   URL: https://www.pexels.com/search/hot%20stone%20massage/"
echo ""
echo "4. Foot Reflexology"
echo "   Search: 'foot reflexology massage'"
echo "   Save as: foot-reflexology-massage.jpg"
echo "   URL: https://www.pexels.com/search/foot%20reflexology/"
echo ""
echo "5. Facial/Head Massage"
echo "   Search: 'head massage spa'"
echo "   Save as: facial-head-massage.jpg"
echo "   URL: https://www.pexels.com/search/head%20massage/"
echo ""
echo "6. Back/Shoulder Massage"
echo "   Search: 'back massage therapy'"
echo "   Save as: back-shoulder-massage.jpg"
echo "   URL: https://www.pexels.com/search/back%20massage/"
echo ""
echo "7. Herbal Compress"
echo "   Search: 'herbal compress massage thai'"
echo "   Save as: herbal-compress-massage.jpg"
echo "   URL: https://www.pexels.com/search/herbal%20compress/"
echo ""
echo "8. Deep Tissue/Sport Massage"
echo "   Search: 'deep tissue massage'"
echo "   Save as: deep-tissue-massage.jpg"
echo "   URL: https://www.pexels.com/search/deep%20tissue%20massage/"
echo ""
echo "9. Luxury Spa/Wellness"
echo "   Search: 'luxury spa wellness'"
echo "   Save as: luxury-spa-wellness.jpg"
echo "   URL: https://www.pexels.com/search/luxury%20spa/"
echo ""
echo "10. Body Treatment/Scrub"
echo "   Search: 'body scrub spa treatment'"
echo "   Save as: body-treatment-scrub.jpg"
echo "   URL: https://www.pexels.com/search/body%20treatment/"
echo ""
echo "================================================"
echo "📁 Save all images to: $(pwd)"
echo "💡 Tip: Download 'Large' or 'Original' size for best quality"
echo "✅ All Pexels images are free to use without attribution"

